### ISSUE TITLE
corregir vista TalleresScreen.js en la rama luis

### ISSUE THREAD

**Issue by alexdevrr05** [alexdevrr05/chatbot-app#7]
- [x] Importar correctamente el componente Slider.js
- [x] Adaptar los estilos de los inputs exactamente igual a los originales
- [x] Corregir funcionalidad del componente Slider.js basándose en la vista ConferenciasScreen.js

**Comment by LuisMariscalDev** [comment]
Listo

**Comment by alexdevrr05** [comment]
Good job
